//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by bpaint.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_TRANSFORMATIONS_PAGE        102
#define IDR_POPUP_FRAME                 118
#define IDD_LAYERSSTRIPVIEW             119
#define IDR_MAINFRAME                   128
#define IDR_BPAINTTYPE                  129
#define IDR_SECONDARY_DOC_TEMPLATE      130
#define IDR_DRAWING_TOOLS               132
#define IDR_QUICK_BRUSHES               134
#define IDR_VIEW_SETTINGS               136
#define IDR_ZOOM_SETTINGS               138
#define IDR_PAINT_MENU_STORAGE          140
#define IDD_CHOOSE_WIDTH_HEIGHT         141
#define IDD_MAKE_STENCIL                146
#define IDD_WINDOW_MANAGE               147
#define IDC_PENCIL_CURSOR               148
#define IDC_MOVE_CURSOR                 149
#define IDC_EDIT_CURSOR                 150
#define IDC_BIG_EDIT_CURSOR             151
#define IDC_FILL_CURSOR                 152
#define IDC_EYEDROP_CURSOR              153
#define IDC_FREEHAND_SINGLE_CURSOR      155
#define IDD_NEW_SHOWCASE                156
#define IDD_SELECT_ANIMATION            157
#define IDD_INSERT_X_DIALOG             159
#define IDD_DELETE_FRAMES               160
#define IDD_CLEAR_LAYERS                161
#define IDD_TRANSFORM_FRAMES            162
#define IDD_ANIMATION_FRAME_LAYER_PAGE  163
#define IDD_SIMPLE_TRANSFORM            164
#define IDD_GRID_INFO                   165
#define IDC_PALETTE_CURSOR              167
#define IDC_CHOOSE_L_COLOR              168
#define IDC_CHOOSE_R_COLOR              169
#define IDR_DEFORMATION_TOOLBAR         170
#define IDD_BRUSH_DEFORMATION           172
#define IDR_ANIMATION_TOOLBAR           173
#define IDD_QUICK_RGB_EDIT              175
#define IDR_UI_LAYOUT_TOOLBAR           176
#define IDC_GRID_CROSS_CURSOR           178
#define IDD_CREATE_ANIM                 179
#define IDR_COMPOSITE_MODE_TOOLBAR      180
#define IDR_SPECIAL_TOOLBAR             182
#define IDB_HAS_CELS                    184
#define IDR_DRAW_SPECIAL                185
#define IDC_STENCIL_CURSOR              187
#define IDD_LAYER_PROPERTIES            188
#define IDD_FRAME_PROPERTIES            189
#define IDD_GOTO_FRAME                  190
#define IDD_COMPOSITE_FRAMES            191
#define IDD_EXPORT_FRAMES               192
#define IDD_TRANSLATE_FRAME_LAYERS      193
#define IDD_ANIM_PROPERTIES             194
#define IDD_ALL_ANIMATION_FRAME_NOTES   195
#define IDD_TEXT_TO_BRUSH               196
#define IDR_ANIM_GRID_FRAME_CONTEXT     197
#define IDR_ANIM_GRID_LAYER_CONTEXT     198
#define IDR_ANIM_GRID_CEL_CONTEXT       199
#define IDR_NAMED_SPOT_ANIM_POPUP       200
#define IDR_NAMED_SPOT_SPOT_POPUP       201
#define IDR_NAMED_SPOT_ADJUSTMENT_POPUP 202
#define IDD_NEW_NAMED_SPOT              203
#define IDD_SPOT_ADJUSTMENT_PROPERTIES  204
#define IDC_OFF_CANVAS_CURSOR           205
#define IDR_SPOT_VIEW_TOOLBAR           206
#define IDR_DRAW_ROPS                   208
#define IDD_COPY_FRAMES                 210
#define IDD_OLD_QUICK_RGB_EDIT          211
#define IDD_EDIT_PALETTE                212
#define IDD_CFO_FLIP_DIALOG             213
#define IDD_BRUSH_GBA_EXPORT            214
#define IDR_VEINFOTB                    215
#define IDD_LOADING_SOMETHING           217
#define IDD_MULTIPAL_QUESTION           218
#define IDB_HAS_PALETTE                 219
#define IDB_REUSED_CEL                  220
#define IDD_PALETTE_MANAGER             221
#define IDD_ENTER_STRING                222
#define ID_SPECIALIZEDWINDOWS_LAYERSSTRIPWINDOW 223
#define ID_SPECIALIZEDWINDOWS_FRAMESSTRIPWINDOW 224
#define ID_SPECIALIZEDWINDOWS_BRUSHWINDOW 225
#define ID_Menu                         226
#define IDD_CREATE_FLATTENED_ANIM       227
#define IDC_WIDTH                       1000
#define IDC_WIDTH_SPIN                  1001
#define IDC_HEIGHT                      1002
#define IDC_HEIGHT_SPIN                 1003
#define IDC_PALETTE                     1004
#define IDC_R_EDIT                      1005
#define IDC_R_SPIN                      1006
#define IDC_G_EDIT                      1007
#define IDC_G_SPIN                      1008
#define IDC_B_EDIT                      1009
#define IDC_B_SPIN                      1010
#define IDC_COLOR_EXAMPLE               1011
#define IDC_COPY                        1012
#define IDC_MOVE                        1013
#define IDC_REVERT                      1014
#define IDC_UNDO                        1015
#define IDC_SPREAD                      1016
#define IDC_SAME_SETTINGS               1017
#define IDC_LIVE_UPDATE_CHECK           1018
#define IDC_SELECTED_COLORS             1019
#define IDC_CLEAR                       1020
#define IDC_INVERT                      1021
#define IDC_USED                        1025
#define IDC_QUICK_EDIT                  1026
#define IDC_SLOT_SETTINGS               1027
#define IDC_OPERATION_COMBO             1028
#define IDC_COLOR_MODE                  1031
#define IDC_LIST                        1033
#define IDC_ACTIVATE                    1034
#define IDC_SAVE                        1035
#define IDC_CLOSE                       1036
#define IDC_CASCADE                     1037
#define IDC_TILEHORZ                    1038
#define IDC_TILEVERT                    1039
#define IDC_MINIMIZE                    1040
#define IDC_SHOWCASE_NAME               1041
#define IDC_CREATE_ANIM_CHECK           1042
#define IDC_CANVAS_SIZE                 1043
#define IDC_ANIMATION_NAME              1044
#define IDC_CANVAS_SIZE_TEXT            1045
#define IDC_FRAMES_EDIT                 1047
#define IDC_FRAMES_SPIN                 1048
#define IDC_LAYERS_EDIT                 1049
#define IDC_LAYERS_SPIN                 1050
#define IDC_ANIMATION_LIST              1052
#define IDC_SHOW_INTERNAL               1053
#define IDC_INSERT_COUNT                1058
#define IDC_INSERT_SPIN                 1059
#define IDC_INSERT_AFTER_CHECK          1060
#define IDC_DUPLICATE                   1061
#define IDC_FROM_EDIT                   1064
#define IDC_FROM_SPIN                   1065
#define IDC_TO_EDIT                     1066
#define IDC_TO_SPIN                     1067
#define IDC_DST_FROM_EDIT               1068
#define IDC_LAYERS_LIST                 1069
#define IDC_DST_FROM_SPIN               1069
#define IDC_ANNOTATIONS_CHECK           1070
#define IDC_DST_TO_EDIT                 1070
#define IDC_FRAME_NOTES_CHECK           1070
#define IDC_IMAGE_CHECK                 1071
#define IDC_DST_TO_SPIN                 1071
#define IDC_OPERATION_TAB               1072
#define IDC_LAYER_NOTES_CHECK           1072
#define IDC_VALIDATE                    1073
#define IDC_COMBO1                      1074
#define IDC_FROM_LAYER_COMBO            1075
#define IDC_HFLIP_CHECK                 1076
#define IDC_VFLIP_CHECK                 1077
#define IDC_MOVE_CHECK                  1078
#define IDC_X_DELTA_EDIT                1079
#define IDC_X_DELTA_SPIN                1080
#define IDC_Y_DELTA_EDIT                1081
#define IDC_X1_EDIT                     1081
#define IDC_Y_DELTA_SPIN                1082
#define IDC_Y1_EDIT                     1082
#define IDC_X_CENTER_EDIT               1083
#define IDC_X2_EDIT                     1083
#define IDC_DDX_EDIT                    1083
#define IDC_X_CENTER_SPIN               1084
#define IDC_Y2_EDIT                     1084
#define IDC_DDX_SPIN                    1084
#define IDC_Y_CENTER_EDIT               1085
#define IDC_X3_EDIT                     1085
#define IDC_DDY_EDIT                    1085
#define IDC_Y_CENTER_SPIN               1086
#define IDC_Y3_EDIT                     1086
#define IDC_DDY_SPIN                    1086
#define IDC_TO_LAYER_COMBO              1087
#define IDC_X4_EDIT                     1087
#define IDC_Y4_EDIT                     1088
#define IDC_ORIGINAL_SIZE_STATIC        1089
#define IDC_OUTPUT_SIZE_STATIC          1090
#define IDC_ANGLE                       1091
#define IDC_SCALE                       1092
#define IDC_SKEW                        1093
#define IDC_RESET                       1094
#define IDC_SLOT_TEXT                   1098
#define IDC_COUNT_TEXT                  1099
#define IDC_EDIT1                       1100
#define IDC_NAME_EDIT                   1100
#define IDC_COLOR_EDIT                  1100
#define IDC_FILENAME_FORMAT_EDIT        1100
#define IDC_LINK_1_X_EDIT               1100
#define IDC_NOTES_EDIT                  1100
#define IDC_TEXT_EDIT                   1100
#define IDC_FRAME_NUMBER_EDIT           1100
#define IDC_ARRAY_NAME                  1100
#define IDC_SLOT_NAME                   1100
#define IDC_EDIT_STRING                 1100
#define IDC_EDIT2                       1101
#define IDC_NOTE_EDIT                   1101
#define IDC_FRAME_EDIT                  1101
#define IDC_FILENAME                    1101
#define IDC_LINK_1_Y_EDIT               1102
#define IDC_VISIBLE_CHECK               1103
#define IDC_LINK_2_X_EDIT               1103
#define IDC_LINK_2_Y_EDIT               1104
#define IDC_LINK_1_X_EDIT2              1104
#define IDC_FRAME_SPIN                  1105
#define IDC_LINK_3_X_EDIT               1105
#define IDC_FRAME_RANGE_STATIC          1106
#define IDC_LINK_3_Y_EDIT               1106
#define IDC_SRC_LAYERS_LIST             1107
#define IDC_LINK_4_X_EDIT               1107
#define IDC_DST_LAYERS_LIST             1108
#define IDC_LINK_4_Y_EDIT               1108
#define IDC_OP_COMBO                    1109
#define IDC_SRC_FROM_EDIT               1110
#define IDC_SRC_FROM_SPIN               1111
#define IDC_SRC_TO_EDIT                 1112
#define IDC_SRC_TO_SPIN                 1113
#define IDC_SRC_ANIM_COMBO              1114
#define IDC_DST_ANIM_COMBO              1115
#define IDC_OUTPUT_START_EDIT           1115
#define IDC_OUTPUT_INC_EDIT             1116
#define IDC_BROWSE                      1117
#define IDC_CODEC_SETTINGS              1119
#define IDC_CODEC_COMBO                 1120
#define IDC_OP_SETTINGS                 1122
#define IDC_SLIDER1                     1123
#define IDC_FRAME_RATE_EDIT             1124
#define IDC_FRAME_RATE_SPIN             1125
#define IDC_NEXT_FRAME                  1126
#define IDC_PREV_FRAME                  1127
#define IDC_PREV_LAYER                  1128
#define IDC_NEXT_LAYER                  1129
#define IDC_LINK_1_CHECK                1130
#define IDC_LINK_2_CHECK                1131
#define IDC_LINK_1_X_SPIN               1131
#define IDC_LINK_3_CHECK                1132
#define IDC_LINK_1_Y_SPIN               1132
#define IDC_LINK_4_CHECK                1133
#define IDC_LINK_2_X_SPIN               1133
#define IDC_FRAME_NUMBER_SPIN           1133
#define IDC_LINK_2_Y_SPIN               1134
#define IDC_LINK_3_X_SPIN               1135
#define IDC_LINK_3_Y_SPIN               1136
#define IDC_LINK_4_X_SPIN               1137
#define IDC_LINK_4_Y_SPIN               1138
#define IDC_SRC_STATIC                  1144
#define IDC_DST_STATIC                  1145
#define IDC_RANGE_INFO                  1146
#define IDC_PALETTE_CHECK               1147
#define IDC_FONT_BUTTON                 1150
#define IDC_LIVE_UPDATES                1155
#define IDC_DELETE_ANIM                 1156
#define IDC_COPY_ANIM                   1157
#define IDC_PROPERTIES                  1158
#define IDC_COPY_TYPE                   1162
#define IDC_R_SCROLLBAR                 1163
#define IDC_G_SCROLLBAR                 1164
#define IDC_B_SCROLLBAR                 1165
#define IDC_PASTE                       1166
#define IDC_REMAP                       1167
#define IDC_FILL                        1169
#define IDC_R_STATIC                    1170
#define IDC_G_STATIC                    1171
#define IDC_B_STATIC                    1172
#define IDC_OVER_STATIC                 1173
#define IDC_RGB_STATIC                  1174
#define IDC_OPERATION_MSG               1177
#define IDC_HEX_CHECK                   1178
#define IDC_SINGLE_DIM_CHECK            1179
#define IDC_MAKE_ELEMENTS               1181
#define IDC_REMOVE_UNUSED               1182
#define IDC_FILE_OFFSET_INDICATOR       1183
#define IDC_RECENT_FILES                1184
#define IDC_RADIO1                      1185
#define IDC_RADIO2                      1186
#define IDC_RADIO3                      1187
#define IDC_ALLOW_LAYER_PALETTES        1188
#define IDC_ALLOW_ANIMATION_PALETTE     1189
#define IDC_CLEAR_ANIM_PALETTE          1190
#define IDC_CLEAR_LAYER_PALETTE         1191
#define IDC_ONLY_LAYER_COLORS           1192
#define IDC_FROM_PARENT                 1193
#define IDC_LOCKED_CHECK                1194
#define IDC_NO_OUTLINE                  1195
#define IDC_OUTLINE_A                   1196
#define IDC_OUTLINE_A_SPIN              1197
#define IDC_OUTLINE_B                   1198
#define IDC_PALETTE_LIST                1198
#define IDC_OUTLINE_B_SPIN              1199
#define IDC_NEW_PALETTE                 1199
#define IDC_COPY_PALETTE                1200
#define IDC_DELETE_PALETTE              1201
#define IDC_EDIT_PALETTE                1202
#define IDC_DESCRIPTION                 1203
#define IDC_RENAME_PALETTE              1204
#define IDC_LOAD_PALETTE                1205
#define IDC_SAVE_PALETTE                1206
#define IDC_PALETTE_PREVIEW             1207
#define IDC_PALETTE_COMBO               1208
#define IDC_ANIMATION_COMBO             1210
#define IDC_CURRENT_FRAME_STATIC        1212
#define IDC_INSERT_LAYER                1213
#define IDC_LAYER_PROPERTIES            1214
#define IDC_AFFECT_CURRENT_FRAME_CHECK  1215
#define IDC_MOVE_LAYER_UP               1216
#define IDC_MOVE_LAYER_DOWN             1217
#define IDC_DELETE_LAYER                1218
#define IDC_LAYERS_LISTBOX              1219
#define IDC_EXPORT_MODE1                1220
#define IDC_EXPORT_MODE2                1221
#define IDC_4BPP_EXPORT                 1222
#define IDC_EXPORT_MODE3                1223
#define IDC_CHECK1                      1224
#define IDC_OUTPUT_PALETTE_CHECK        1224
#define IDC_INDEPENDENT                 1224
#define IDC_INDEPENDENT_LAYERS_MODE     1224
#define IDC_PIXEL_ASPECT_TEXT           1225
#define IDC_BUTTON1                     1226
#define IDC_SET_PIXEL_ASPECT_RATIO      1226
#define IDC_8BIT_PACKING                1227
#define IDC_16BIT_PACKING               1228
#define IDC_32BIT_PACKING               1229
#define IDC_RGB555_OUTPUT               1230
#define IDC_GENERATE_SHADE_TABLE        1231
#define IDC_TILE_WIDTH_EDIT             1232
#define IDC_TILE_W_EDIT                 1232
#define IDC_TILE_H_EDIT                 1233
#define IDC_SCROLLBAR1                  1233
#define IDC_SELECTED_LAYERS             1234
#define ID_REFRESH                      32783
#define ID_DTOOL_FREEHAND_LINE          32784
#define ID_DTOOL_FREEHAND_SPOTTY        32785
#define ID_DTOOL_FREEHAND_SINGLE        32786
#define ID_DTOOL_LINE                   32787
#define ID_DTOOL_3PT_CURVE              32788
#define ID_DTOOL_SOLID_RECT             32789
#define ID_DTOOL_EMPTY_RECT             32790
#define ID_DTOOL_SOLID_ELLIPSE          32791
#define ID_DTOOL_EMPTY_ELLIPSE          32792
#define ID_DTOOL_CROP_RECT              32793
#define ID_DTOOL_FLOOD_FILL             32794
#define ID_DTOOL_EYE_DROPPER            32795
#define ID_DTOOL_PICKUP_BRUSH           32796
#define ID_DTOOL_STAMP_BRUSH            32797
#define ID_DTOOL_GRID                   32798
#define ID_DTOOL_UNDO                   32799
#define ID_DTOOL_CLEAR                  32800
#define ID_DTOOL_EMPTY_CIRCLE           32801
#define ID_DTOOL_SOLID_CIRCLE           32802
#define ID_DTOOL_EMPTY_SQUARE           32803
#define ID_DTOOL_SOLID_SQUARE           32804
#define ID_VIEW_DRAWING_TOOLS           32806
#define ID_QBRUSH_ELLIPSE_0             32807
#define ID_QBRUSH_ELLIPSE_1             32808
#define ID_QBRUSH_ELLIPSE_2             32809
#define ID_QBRUSH_ELLIPSE_3             32810
#define ID_QBRUSH_ELLIPSE_4             32811
#define ID_QBRUSH_SIZE_INC              32812
#define ID_QBRUSH_SIZE_DEC              32813
#define ID_QBRUSH_ELLIPSE_N             32814
#define ID_VIEW_QUICK_BRUSHES           32822
#define ID_VIEW_VIEW_SETTINGS           32824
#define ID_VIEW_ZOOM_SETTINGS           32825
#define ID_VSET_DISABLE_EDIT            32826
#define ID_VSET_DISABLE_AUTO_SCROLL     32827
#define ID_VZOOM_1X                     32828
#define ID_VZOOM_2X                     32829
#define ID_VZOOM_3X                     32830
#define ID_VZOOM_4X                     32831
#define ID_VZOOM_5X                     32832
#define ID_VZOOM_6X                     32833
#define ID_VZOOM_7X                     32834
#define ID_VZOOM_8X                     32835
#define ID_VZOOM_9X                     32836
#define ID_VZOOM_10X                    32837
#define ID_VZOOM_INC                    32838
#define ID_VZOOM_DEC                    32839
#define ID_VIEW_AUTO_FOCUS              32842
#define ID_VSET_COMPOSITE_MODE          32843
#define ID_VSET_SHOW_GRID               32844
#define ID_VSET_SHOW_FATBITS            32845
#define ID_VCMD_CENTER_ON_CURSOR        32846
#define ID_VCMD_CURSOR_ZOOM             32847
#define ID_2_REFRESH                    32848
#define ID_2_DTOOL_FREEHAND_LINE        32849
#define ID_2_DTOOL_FREEHAND_SPOTTY      32850
#define ID_2_DTOOL_FREEHAND_SINGLE      32851
#define ID_2_DTOOL_LINE                 32852
#define ID_2_DTOOL_3PT_CURVE            32853
#define ID_2_DTOOL_SOLID_RECT           32854
#define ID_2_DTOOL_EMPTY_RECT           32855
#define ID_2_DTOOL_SOLID_ELLIPSE        32856
#define ID_2_DTOOL_EMPTY_ELLIPSE        32857
#define ID_2_DTOOL_CROP_RECT            32858
#define ID_2_DTOOL_FLOOD_FILL           32859
#define ID_2_DTOOL_EYE_DROPPER          32860
#define ID_2_DTOOL_PICKUP_BRUSH         32861
#define ID_2_DTOOL_STAMP_BRUSH          32862
#define ID_2_DTOOL_GRID                 32863
#define ID_2_DTOOL_UNDO                 32864
#define ID_2_DTOOL_CLEAR                32865
#define ID_2_DTOOL_EMPTY_CIRCLE         32866
#define ID_2_DTOOL_SOLID_CIRCLE         32867
#define ID_2_DTOOL_EMPTY_SQUARE         32868
#define ID_2_DTOOL_SOLID_SQUARE         32869
#define ID_2_QBRUSH_ELLIPSE_0           32870
#define ID_2_QBRUSH_ELLIPSE_1           32871
#define ID_2_QBRUSH_ELLIPSE_2           32872
#define ID_2_QBRUSH_ELLIPSE_3           32873
#define ID_2_QBRUSH_ELLIPSE_4           32874
#define ID_2_QBRUSH_SIZE_INC            32875
#define ID_2_QBRUSH_SIZE_DEC            32876
#define ID_2_QBRUSH_ELLIPSE_N           32877
#define ID_NEW_POPUP_VIEW               32880
#define ID_EDIT_PALETTE                 32881
#define IDS_WINDOW_MANAGE               32882
#define ID_WINDOW_MANAGE                32883
#define ID_COLOR_INC                    32884
#define ID_COLOR_DEC                    32885
#define ID_COLOR_SET                    32886
#define ID_COLOR_PREVIOUS               32887
#define ID_2_COLOR_INC                  32888
#define ID_2_COLOR_DEC                  32889
#define ID_2_COLOR_SET                  32890
#define ID_2_COLOR_PREVIOUS             32891
#define ID_VFRAME_SHOW_ZOOM_TOOLBAR     32892
#define ID_VFRAME_SHY_ZOOM_TOOLBAR      32893
#define ID_VSET_IMEDIATE_UPDATES        32894
#define ID_HACK_LOAD_BACKGROUND         32895
#define ID_HACK_LOAD_FOREGROUND         32896
#define ID_ANIM_INSERT_FRAMES           32898
#define ID_ANIM_DELETE_FRAMES           32899
#define ID_ANIM_INSERT_LAYERS           32900
#define ID_ANIM_DELETE_LAYERS           32901
#define ID_ANIM_PROPERTIES              32902
#define ID_ANIM_ANNOTATIONS             32903
#define ID_FRAME_PROPERTIES             32904
#define ID_FRAME_ANNOTATIONS            32905
#define ID_LAYER_ANNOTATIONS            32906
#define ID_LAYER_PROPERTIES             32907
#define ID_FRAME_TRANSFORMATIONS        32908
#define ID_FRAME_CLEAR_CEL              32909
#define ID_FRAME_CLEAR_IMAGE            32910
#define ID_FRAME_CLEAR                  32911
#define ID_LAYER_CLEAR                  32912
#define ID_LAYER_LOAD_FRAMES            32913
#define ID_LAYER_SAVE_FRAMES            32914
#define ID_LAYER_EXPORT_FRAMES          32915
#define ID_LAYER_IMPORT_FRAMES          32916
#define ID_LAYER_LOCK                   32917
#define ID_EDIT_STENCIL                 32918
#define ID_GLOBAL_SETTINGS              32919
#define ID_LAYER_VISIBLE                32920
#define ID_ANIM_MAKE_ANIMBRUSH          32922
#define ID_ANIM_SAVE_AS_SHOWCASE        32923
#define ID_ANIM_SELECT                  32924
#define ID_ANIM_SELECT_DIALOG           32925
#define ID_FRAME_NEXT                   32926
#define ID_FRAME_PREV                   32927
#define ID_FRAME_GOTO                   32928
#define ID_ANIM_PLAY                    32929
#define ID_LAYER_PREV                   32930
#define ID_LAYER_NEXT                   32931
#define ID_ANIM_NEXT                    32932
#define ID_ANIM_PREV                    32933
#define ID_ANIM_IMPORT_FROM_SHOWCASE    32934
#define ID_BRUSH_HFLIP                  32935
#define ID_BRUSH_VFLIP                  32936
#define ID_BRUSH_ROTATE_90              32937
#define ID_BRUSH_DOUBLE_WIDTH           32938
#define ID_BRUSH_DOUBLE_HEIGHT          32939
#define ID_BRUSH_DOUBLE_SIZE            32940
#define ID_BRUSH_RESTORE                32941
#define ID_BRUSH_HALVE_SIZE             32942
#define ID_BRUSH_STRETCH                32943
#define ID_VZOOM_VISUAL                 32944
#define ID_BRUSH_NEXT_FRAME             32945
#define ID_BRUSH_PREV_FRAME             32946
#define ID_BRUSH_HANDLE_CENTER          32947
#define ID_BRUSH_HANDLE_TOPLEFT         32948
#define ID_BRUSH_HANDLE_BOTTOMRIGHT     32949
#define ID_VSET_CENTER_SYNC_SCROLL      32950
#define ID_BRUSH_HANDLE_DEFAULT         32951
#define ID_NEW_SIMPLE_PALETTE_VIEW      32953
#define ID_PAINT_TRIM_EDGE              32954
#define ID_VCMD_REQUEST_OTHERS_CENTER_ON_CURSOR 32955
#define ID_HELPER_CYCLE_FREEHAND_TOOL   -32580
#define ID_RETURN_TO_BUILT_IN_BRUSH     32957
#define ID_BRUSH_CUSTOM_DEFORMATION     32961
#define ID_VIEW_BRUSH_XFORM             32962
#define ID_BRUSH_OUTLINE                32968
#define ID_ANIM_REWIND                  32969
#define ID_BUTTON32972                  32972
#define ID_ANIM_STOP                    32972
#define ID_ANIM_FASTFORWARD             32974
#define ID_VIEW_PLAYBACK_TOOLBAR        32981
#define ID_HACK_LOAD_PICTURE            32982
#define ID_HACK_SAVE_PICTURE            32983
#define ID_UI_LAYOUT_1                  32986
#define ID_UI_LAYOUT_2                  32987
#define ID_UI_LAYOUT_3                  32988
#define ID_UI_LAYOUT_4                  32989
#define ID_UI_LAYOUT_5                  32990
#define ID_UI_LAYOUT_6                  32991
#define ID_UI_LAYOUT_7                  32992
#define ID_UI_LAYOUT_SETTINGSA          32996
#define ID_VIEW_LAYOUT_TOOLBAR          32997
#define ID_ANIM_CREATE                  33004
#define ID_VIEW_EXPAND                  33005
#define ID_COMPOSITE_BOUNDING_RECTS     33007
#define ID_COMPOSITE_EXTERNAL_RECT      33008
#define ID_COMPOSITE_SHOW_HANDLES       33009
#define ID_VIEW_COMPOSITE_TOOLBAR       33010
#define ID_COMPOSITE_MODE               33012
#define ID_COMPOSITE_SET_ANIM_MAIN_LINK 33015
#define ID_COMPOSITE_SET_LINK_1         33016
#define ID_COMPOSITE_SET_LINK_2         33017
#define ID_COMPOSITE_SET_LINK_3         33018
#define ID_COMPOSITE_SET_LINK_4         33019
#define ID_COMPOSITE_X_LOCK             33020
#define ID_BUTTON33021                  33021
#define ID_COMPOSITE_Y_LOCK             33022
#define ID_COMPOSITE_OPAQUE             33023
#define ID_PENDING_MODE                 33024
#define ID_REQUEST_PENDING_MODE         33025
#define ID_RENDER_FOREGROUND_5050       33026
#define ID_RENDER_CHECKER_BOARD_BACKDROP 33030
#define ID_SHOW_SPECIAL_TOOLBAR         33031
#define ID_COMPOSITE_RENDER_SELECTED    33032
#define ID_COMPOSITE_DISABLE_IMAGE_RENDER 33033
#define ID_LAYER_COPY_FRAME_TO_NEXT     33034
#define ID_CENTER_VIEW                  33035
#define ID_NEW_POPUP_GRID_VIEW          33036
#define ID_SPECIAL_CASE_OPAQUE_EDIT     33037
#define ID_2_FRAME_PREV                 33038
#define ID_2_FRAME_NEXT                 33039
#define ID_2_LAYER_PREV                 33040
#define ID_2_LAYER_NEXT                 33041
#define ID_2_RENDER_FOREGROUND_5050     33042
#define ID_2_VSET_COMPOSITE_MODE        33043
#define ID_NEW_MDI_GRID                 33044
#define ID_NEW_MULTI_SPLIT_WINDOW       33045
#define ID_ANIM_DELETE_SINGLE_LAYER     33046
#define ID_SHIFT_DRAW_CANVAS_U          33047
#define ID_SHIFT_DRAW_CANVAS_D          33048
#define ID_SHIFT_DRAW_CANVAS_L          33049
#define ID_SHIFT_DRAW_CANVAS_R          33050
#define ID_HFLIP_DRAW_CANVAS            33051
#define ID_VFLIP_DRAW_CANVAS            33053
#define ID_OUTLINE_DRAW_CANVAS          33054
#define ID_VIEW_DRAW_SPECIAL_TOOLBAR    33055
#define ID_PLAY_ANIM_NEXT_FRAME         33057
#define ID_PLAY_ANIM_STOP               33058
#define ID_PLAY_ANIM_START              33059
#define ID_STENCIL_ON                   33060
#define ID_COMPOSITE_SHOW_LINKPOINTS    33062
#define ID_GRID_SETTINGS                33063
#define ID_FRAME_COMPOSITE_OPS          33064
#define ID_TRANSLATE_FRAME_LAYERS       33065
#define ID_ANIM_LOAD_BACKDROP           33066
#define ID_ANIM_CLEAR_BACKDROP          33067
#define ID_ANIM_SHOW_BACKDROP           33068
#define ID_HACK_LOAD_PALETTE            33069
#define ID_HACK_GRID_THUMBNAILS         33070
#define ID_ALL_ANIMATION_FRAME_NOTES    33071
#define ID_HACK_TRANSPARENT_THUMBNAIL_SCALE 33073
#define ID_SHOWCASE_CHANGE_CANVAS       33074
#define ID_BRUSH_TEXT_TO_BRUSH          33075
#define ID_ANIM_SPECIAL_CAPTURE_FONT    33077
#define ID_SPECIAL_IMEDIATE_SILENT_RENDER 33078
#define ID_UI_STORE_LAYOUT_8            33080
#define ID_UI_STORE_LAYOUT_9            33081
#define ID_UI_STORE_LAYOUT_0            33082
#define ID_UI_LAYOUT_ETC                33083
#define ID_NEW_WINDOW_CLIP              33084
#define ID_NEW_MDI_ANIM_LIST            33085
#define ID_NEW_MDI_ANIM_SPOTS           33086
#define ID_NSPOT_CREATE_NEW             33087
#define ID_NSPOT_DELETE_SPOT            33088
#define ID_NSPOT_SPOT_PROPERTIES        33089
#define ID_NSPOT_NEW_SPOT_ADJUSTMENT    33090
#define ID_NSPOT_ADJUSTMENT_PROPERTIES  33091
#define ID_NSPOT_NEW_ADJUSTMENT         33092
#define ID_NSPOT_DELETE_ADJUSTMENT      33093
#define ID_MODIFY_NAMED_SPOT            33094
#define ID_MODIFY_SPOT_ADJUSTMENT       33095
#define ID_DELETE_SPOT_OR_ADJUSTMENT    33096
#define ID_EDIT_PROPERTIES              33097
#define ID_EDIT_SPOT_PROPERTIES         33098
#define ID_NEW_NAMED_SPOT               33099
#define ID_CREATE_SPOT_ADJUSTMENT       33100
#define ID_NEW_POPUP_ANIM_SPOTS         33103
#define ID_ROP_SINGLE_COLOR             33104
#define ID_ROP_MATTE                    33105
#define ID_ROP_REPLACE                  33106
#define ID_ROP_DIFFERENCE               33107
#define ID_ROP_KEEP_SAME                33108
#define ID_ROP_KEEP_DIFF                33109
#define ID_VIEW_ROP_TOOLBAR             33113
#define ID_REMEMBER_TOOLBAR_SIZES       33114
#define ID_COPY_FRAMES                  33115
#define ID_UI_LAYOUT_8                  33993
#define ID_UI_LAYOUT_9                  33994
#define ID_UI_LAYOUT_0                  33995
#define ID_COPY                         33996
#define ID_PASTE                        33997
#define ID_BRUSH_EXPORT_GBA_DATA        33998
#define ID_NEW_MDI_VE_INFO              33999
#define ID_VEMODE_SIMPLE                34000
#define ID_VEMODE_REPLACE_ASK           34001
#define ID_VEMODE_REPLACE_DONT_ASK      34002
#define ID_SHOWCASE_OPTIMIZE            34003
#define ID_NEW_POPUP_VE_INFO            34004
#define ID_CLICK_SELECT_LAYER           34005
#define ID_FILL_ACROSS_LAYERS           34007
#define ID_TPB_XML_EXPORT               34009
#define ID_TPB_XML_IMPORT               34010
#define ID_GRID_SHOW_UIDS               34011
#define ID_FATBITS_COLOR_USE_CHROMAKEY  34012
#define ID_MANAGE_PALETTES              34018
#define ID_CHANGE_PIXEL_ASPECT_RATIO    34023
#define ID_LOAD_PICTURE_FROM_CLIPBOARD  34024
#define ID_ANIM_SPECIAL_BRUSH_TO_ANIM   34025
#define ID_ANIM_SPECIAL_EXPORT_TO_CODE  34026
#define ID_SPECIAL_BREAKDOWNANIMATIONVISUALS 34028
#define ID_SPECIAL_SUPER_OPTIMIZE       34029
#define ID_BRUSH_TO_LAYERED_ANIM        34031
#define ID_Menu34032                    34032

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        228
#define _APS_NEXT_COMMAND_VALUE         34033
#define _APS_NEXT_CONTROL_VALUE         1235
#define _APS_NEXT_SYMED_VALUE           120
#endif
#endif
